import test from 'node:test';
import assert from 'node:assert/strict';
import 'fake-indexeddb/auto';
import { EMPTY_FORM } from '../src/lib/form.js';
import { readDraft, saveDraft, clearDraft, submitProfile, deleteSubmission, summaryText } from '../src/lib/storage.js';
const data={...EMPTY_FORM,firstName:'Alex',lastName:'Chen',email:'alex@example.com',phone:'+1 202 555 0123',nationality:'Singaporean',language:'English',address:'10 Example Road',city:'Singapore',country:'Singapore',consent:true};
const file=()=>new File(['%PDF-1.7\nDemo fixture'],'resume.pdf',{type:'application/pdf'});
function memoryStorage(){const entries=new Map();return{getItem:key=>entries.get(key)??null,setItem:(key,value)=>entries.set(key,value),removeItem:key=>entries.delete(key),entries};}
function readRecord(id){return new Promise((resolve,reject)=>{const open=indexedDB.open('hpair-passport-v1',1);open.onsuccess=()=>{const db=open.result;const request=db.transaction('submissions').objectStore('submissions').get(id);request.onsuccess=()=>{resolve(request.result);db.close();};request.onerror=reject;};open.onerror=reject;});}
test('draft round-trip drops consent and expires after seven days',()=>{const storage=memoryStorage();saveDraft(data,storage);assert.equal(readDraft(storage).firstName,'Alex');assert.equal(readDraft(storage).consent,false);const [key,value]=[...storage.entries][0];storage.setItem(key,JSON.stringify({...JSON.parse(value),updatedAt:Date.now()-8*86400000}));assert.equal(readDraft(storage),null);assert.equal(storage.entries.size,0);});
test('malformed and unavailable draft storage do not crash hydration',()=>{const storage=memoryStorage();storage.setItem('hpair-passport-draft-v1','{broken');assert.equal(readDraft(storage),null);assert.equal(readDraft({getItem(){throw new Error('unavailable');}}),null);});
test('draft hydration strips malformed fields and ignores unknown fields',()=>{const storage=memoryStorage();storage.setItem('hpair-passport-draft-v1',JSON.stringify({version:1,updatedAt:Date.now(),data:{firstName:123,interests:'bad',consent:true,unknown:'hidden'}}));const draft=readDraft(storage);assert.equal(draft.firstName,'');assert.deepEqual(draft.interests,[]);assert.equal(draft.consent,false);assert.equal(draft.unknown,undefined);});
test('turning off draft retention removes stored personal data',()=>{const storage=memoryStorage();saveDraft(data,storage);clearDraft(storage);assert.equal(readDraft(storage),null);});
test('storage quota errors propagate to the UI',()=>{assert.throws(()=>saveDraft(data,{setItem(){throw new Error('quota');}}),/quota/);});
test('submission commits a real record and retry keeps the same ID',async()=>{const first=await submitProfile(data,file(),'same-id');assert.equal(first.id,'same-id');assert.equal((await readRecord('same-id')).data.firstName,'Alex');await submitProfile({...data,firstName:'Updated'},file(),'same-id');assert.equal((await readRecord('same-id')).data.firstName,'Updated');});
test('submission rejects invalid details and spoofed PDFs before writing',async()=>{await assert.rejects(submitProfile(EMPTY_FORM,file(),'invalid'),/attention/);await assert.rejects(submitProfile(data,new File(['fake'],'cv.pdf',{type:'application/pdf'}),'spoof'),/attention/);assert.equal(await readRecord('invalid'),undefined);assert.equal(await readRecord('spoof'),undefined);});
test('receipt download includes profile details but no file bytes',async()=>{const receipt=await submitProfile(data,file(),'summary-id');const text=summaryText(receipt);assert.match(text,/alex@example.com/);assert.match(text,/resume.pdf/);assert.match(text,/not sent to HPAIR/);assert.doesNotMatch(text,/%PDF/);});
test('deletion removes a saved profile and succeeds on repeated requests',async()=>{await submitProfile(data,file(),'delete-id');await deleteSubmission('delete-id');assert.equal(await readRecord('delete-id'),undefined);await deleteSubmission('delete-id');});
